### ISSUE TITLE
Error getting devices: Error: ENOENT: no such file or directory, open '/var/lib/hoobs/wyzeconnectedhomeopbridge/persist/wyze-[uuid removed].json'

### ISSUE THREAD

**Issue by theonlynewts** [RMCob/homebridge-wyze-connected-home-op#10]
I'm getting an error when trying to set up this plugin for the first time on my first exposure to Hoobs. I'm not really sure what information is helpful, but I found there is no "persist" directory in the directory referenced. 
`Error getting devices: Error: ENOENT: no such file or directory, open '/var/lib/hoobs/wyzeconnectedhomeopbridge/persist/wyze-[uuid removed].json'`
![image](https://user-images.githubusercontent.com/4991928/143272824-519ceb09-bdef-4ea8-bea5-2be0cdb957a2.png)

I also found this post on reddit with no response with the same issue from about 3 months ago except they mention "half the time" it does this, but for me it's consistent.
https://www.reddit.com/r/HOOBS/comments/pf6o3k/wyze_plugin_issues_since_update_to_4/

https://github.com/RMCob/homebridge-wyze-connected-home-op/blob/ee93c8043d66cc350750843022de81e1ecc9b45e/src/WyzeAPI.js#L182

**Comment by RMCob** [comment]
This plugin was written for Homebridge, not Hoobs. I have no idea what the Hoobs infrastructure may or may not be doing behind the scenes. You can always resolve the problem by opening a terminal window and creating the missing directory manually. ex: $ mkdir  /var/lib/hoobs/wyzeconnectedhomeopbridge/persist
