### ISSUE TITLE
Support for V2 contact and motion sensors

### ISSUE THREAD

**Issue by holocronology** [RMCob/homebridge-wyze-connected-home-op#12]
Is there any plan to add support for the version 2 contact and motion sensors?

**Comment by RMCob** [comment]
Since I do not have any V2 sensors or the base to test with I cannot do it.

**Comment by sisuwest** [comment]
the V2 sensors are already supported. I see all of them in Apple Home and they update just fine.

I've attached my log as proof.

[log-2.txt](https://github.com/RMCob/homebridge-wyze-connected-home-op/files/7780933/log-2.txt)

**Comment by holocronology** [comment]
Indeed, they do. I just upgraded to this plugin. ;-)
