### ISSUE TITLE
Wyze Light Strip & Pro Support 

### ISSUE THREAD

**Issue by zxlin** [RMCob/homebridge-wyze-connected-home-op#17]
Thanks for the great work on this repo. I'm wondering what it'll take to get the Light Strips to work with this. I have the Light Strip Pros and I can test. Intuitively, it seems like the API should be similar to the Color Bulbs. If you can give me some pointers I can test and submit a PR. Thanks!

**Comment by RMCob** [comment]
Can you send me email (rob@polymorphic-services.com) so I can get your email address and we can take this thread off GitHub until we get it working? Thanks!

**Comment by RMCob** [comment]
This has been implemented in V0.5.9. Thanks to (https://github.com/zxlin) for his beta testing help.
