### ISSUE TITLE
Log data/window in Homebridge

### ISSUE THREAD

**Issue by holocronology** [RMCob/homebridge-wyze-connected-home-op#18]
Plugin appears to be showing a huge amount of data in the logs window in Homebridge. Is this expected behaviour? Just seems like a lot and I don't recall it doing that recently:
![image](https://user-images.githubusercontent.com/65265114/149139405-722d7b67-0069-4d1d-8ae1-ce6dca94623b.png)

**Comment by RMCob** [comment]
You must be running the beta version. Revert back to V0.5.8 to reduce the extra log output it it’s bothering you.

**Comment by holocronology** [comment]
It was, in fact the "beta" version but that's what installed. Evidently it just updated to 0.5.9 not-beta. IDK.

Thanks.
