### ISSUE TITLE
Adaptive Lighting

### ISSUE THREAD

**Issue by mikezio** [RMCob/homebridge-wyze-connected-home-op#19]
Is there any way to enable the native Adaptive Lighting feature in HomeKit for use with the Wyze bulbs? I have the option using the Govee plugin, but not for the Wyze bulbs.
Thanks!

**Comment by RMCob** [comment]
As far as I know HomeKit adaptive lighting is only available for bulbs that support it, and Wyze bulbs do not, so the short answer is no.

**Comment by ArmandAgopian** [comment]
Hi, as of Homebridge version 1.3.0, adaptive lighting is available to enable on all homebridge lightbulb plugins. I am not sure how to implement it, however.
