### ISSUE TITLE
Plugin no longer working.

### ISSUE THREAD

**Issue by ghost** [RMCob/homebridge-wyze-connected-home-op#27]
I've just posted this on the Discord Channel for Homebridge:

Wyze RMCob's Homebridge-wyze-connected-home-op suddenly stopped working this week. Error messages include: [09/04/2022, 09:48:30] [Wyze] Error getting devices: TypeError: Cannot read property 'r' of null;  I haven't changed any settings. Does anyone know if Wyze changed something on their end? I cannot use Homebridge to control scenes and the accessories do not show up.

Would appreciate any help you can provide.

Am running Homebridge on a Raspberry Pi with all software updated. Any ideas?

**Comment by RMCob** [comment]
@rahaim I believe this was a Wyze issue. If you are still having this problem we can reopen the issue. As of yesterday things seem to be working smoothly again.
