### ISSUE TITLE
Would someone be willing to help with creating a development machine for this project?

### ISSUE THREAD

**Issue by jfarmer08** [RMCob/homebridge-wyze-connected-home-op#30]

**Comment by RMCob** [comment]
What exactly do you mean "development machine"? Please be more specific.

**Comment by jfarmer08** [comment]
I was having issues setting my machine up to develop for homebridge plugins. I have it running fine now. 

Are you currently maintaining the wyze plugin? If so will you accept a pull request for support of Temp sensors and water sensors?  If not I can create a separate repo.
