### ISSUE TITLE
Updated to V0.5.6. Includes 403 error fix and initial support for color bulbs.

### ISSUE THREAD

**Issue by RMCob** [RMCob/homebridge-wyze-connected-home-op#4]
I have updated RMCob/homebridge-wyze-connected-home-op to incorporate the fixes for the 403 error and Color Bulb functionality supplied by others. I do not have a Color Bulb to verify those changes but the 403 error is definitely fixed (until something else changes :-))

**Comment by coledeb** [comment]
Thank you @RMCob for merging this! Going forward, I will continue to look out for and test potential upgrades or features added via issues, requests, etc. on your fork or the original project. In regards to devices that you do not own yourself, I will test what I am able and open pull requests when I am able to verify working functionality, but I understand your hesitation to merge what you are not able to test, and I appreciate you doing so for the color bulb functionality (which has still been working without issue for me).

**Comment by johnecampos** [comment]
Forgive my lack of knowledge on this, but how do I find V0.5.6 to install; I seem to be able to only find up to 5.3. I and have a 403 error issue I'd like to resolve. I have prior installed 5.4 (which allowed my color bulbs) but in migrating to a new computer I could only install v0.5.3.  Thank you in advance.  (I was using "npm install https://github.com/RMCob/homebridge-wyze-connected-home-op"

**Comment by RMCob** [comment]
The simplest way is to use the Homebridge UI (homebridge-config-ui-x) and search for 'homebridge-wyze-connected-home-op' which should offer the latest version.

**Comment by johnecampos** [comment]
Thank you, however it is only offering 5.3 as the latest version. Was looking how to install 5.6. Thank you. 
<img width="573" alt="Screen Shot 2021-08-19 at 2 57 26 PM" src="https://user-images.githubusercontent.com/79477144/130149766-8fba5f79-1571-4b68-94d9-da7ae0f0d94c.png">

PS: I downloaded the files and installed it using "npm install -g ~/homebridge-wyze-connected-home-op-0.5.6.tar.gz"; however, the UI still says 5.3 is the latest version FYI.

**Comment by RMCob** [comment]
I tried installing the plug-in via the GUI and indeed it only offers V0.5.3 as the latest. While I investigate this, use this command to manually install the latest version: 
     sudo npm install -I -g https://github.com/RMCob/homebridge-wyze-connected-home-op

**Comment by Jakmc25** [comment]
Any luck on figuring out why the GUI doesn't show V5.6? i can't get the install command to work

**Comment by RMCob** [comment]
I am having a problem 'Publishing' the latest version to npm. In the meantime use the following command from a terminal command line:
sudo npm install -I -g https://github.com/RMCob/homebridge-wyze-connected-home-op

**Comment by dshamgin** [comment]
> I am having a problem 'Publishing' the latest version to npm. In the meantime use the following command from a terminal command line: sudo npm install -I -g https://github.com/RMCob/homebridge-wyze-connected-home-op

Anything I can help you with in regards to publishing the update to npm?

**Comment by RMCob** [comment]
> > I am having a problem 'Publishing' the latest version to npm. In the meantime use the following command from a terminal command line: sudo npm install -I -g https://github.com/RMCob/homebridge-wyze-connected-home-op
> 
> Anything I can help you with in regards to publishing the update to npm?

Thanks for the offer which prompted me to try again. I had been having problems with "npm login" and supplying a one-time password. Once I sorted all that out doing the "npm publish" was easy. :-)
