### ISSUE TITLE
Keep getting 403 error with correct credentials

### ISSUE THREAD

**Issue by neilio** [RMCob/homebridge-wyze-connected-home-op#6]
Hello! I'm glad to have found this fork as the original plugin had stopped working for me. I'm running into an issue where I can't get the plugin to authenticate. I'm positive I'm using the correct email and password and I've turned 2FA off but I keep getting the following error:

```
[8/7/2021, 7:13:28 PM] [Wyze] Request failed: Error: Request failed with status code 403
[8/7/2021, 7:13:28 PM] [Wyze] Response (Forbidden): {"description":"Request forbidden."}
[8/7/2021, 7:13:28 PM] [Wyze] Error getting devices: Error: Request failed with status code 403
```

**Comment by coledeb** [comment]
@neilio just to make sure, are you using the version that was released 3 days ago? I would suggest completely removing the plugin and re-adding it to ensure that it is latest. The fix incorporated in that release has been working for me flawlessly through multiple restarts of my server and even adding a new bulb in the interim.

**Comment by neilio** [comment]
Hey, thanks for the reply. I installed from npm and you were correct that it was an older version. I have the new version installed and everything is working now.
