### ISSUE TITLE
Feature idea: Exposing Wyze cam detection events to homebridge as a dummy presence sensor

### ISSUE THREAD

**Issue by TristanBrotherton** [RMCob/homebridge-wyze-connected-home-op#7]
I'm aware of the issues integrating Wyze cameras into homebridge. However, what about exposing them as a dummy motion sensor that was triggered on either a) motion or b) a chosen Wyze AI event such as person detection? It could lead to some pretty cool hacks.

The UI could allow you to configure the mapping to a camera and set the selected Wyze AI event (person, pet, package etc) to trigger the sensor.

This could then be used to create alarm systems and all sorts of fun stuff...

**Comment by RMCob** [comment]
The Wyze API does not expose camera events. The closest you can get is to use IFTTT and trigger on motion (AI events not available via IFTTT) and then do whatever action you want.

**Comment by TristanBrotherton** [comment]
I know this issue was closed, but I wondered as a potential solution, if you got access to push notifications if you could trigger a homebridge contact sensor for the relevant AI event that way? Theres a fair bit of interest in this: https://www.reddit.com/r/wyzecam/comments/q8bc3n/exposing_wyze_cam_detection_events_to_homekithome/
