### ISSUE TITLE
I can't see the device into homekit

### ISSUE THREAD

**Issue by fortil** [RMCob/homebridge-wyze-connected-home-op#9]
Everything looks ok but I can't see anything into my Home iPhone application.
I can use it into homebridge accessories but not into home app

**Comment by RMCob** [comment]
Do you have other Homebridge devices(i.e. not Wyze) that are visible in HomeKit? If nothing is visible then you have a connectivity issue between Homebridge and Homekit that you will have to go elsewhere to solve.
